### ISSUE TITLE
Consider replacing RocksDB

### ISSUE THREAD

**Issue by Asurar0** [Sweattypalms/ferrumc#5]
First of all, I wanted to express my admiration for your work on FerrumC, which I recently came across on r/rust. Your project is truly impressive, and I am excited about its current capabilities.

I would appreciate the opportunity to discuss with you the potential of replacing RocksDB with alternative databases, such as LMDB or MDBX, which offer improved read performance, reduced overhead, and increased versatility. As you may be aware, RocksDB's [LSM](https://en.wikipedia.org/wiki/Log-structured_merge-tree) architecture prioritizes write throughput, whereas [B+Tree](https://en.wikipedia.org/wiki/B%2B_tree)-based databases like LMDB and MDBX provide higher read throughput and logarithmic time complexity for CRUD operations, albeit with increased write latency (due to write amplifications).

It appears that many Minecraft servers would likely derive greater benefits from optimized read performance, given the typical patterns of players. If you are open to exploring this option, I would be happy to create a fork of the repository to implement MDBX

For further information on the trade-offs between different key-value storage engines, including RocksDB, you may find the following resource from the Erigon Ethereum node project helpful: https://github.com/erigontech/erigon/wiki/Choice-of-storage-engine

**Comment by Sweattypalms** [comment]
I see, that's interesting. Let's discuss in the discord server.

**Comment by ReCore-sys** [comment]
We have tried a few databases and so far rocksdb is the only one that doesn't seem to have major upfront issues. That being said, we are absolutely considering alternatives so will look into the ones you've mentioned.
